/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.CityHistory;
import Model.CommunityHistory;
import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.HospitalDirectory;
import Model.HouseHistory;
import Model.PatientDirectory;
import Model.PersonDirectory;
import Model.Vitals;

/**
 *
 * @author sumit
 */
public class CommunityAdminHomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdminHomeJFrame
     */
    public static PersonDirectory personDirectory;
    public static PatientDirectory patientDirectory;
    public static CityHistory cityHistory;
    public static CommunityHistory communityHistory;
    public static HouseHistory houseHistory;
    public static EncounterHistory encounterHistory;
    public static DoctorDirectory doctorDirectory;
    public static HospitalDirectory hospitalDirectory;
    public static Vitals vitals;
    public CommunityAdminHomeJFrame(PersonDirectory personDirectory, PatientDirectory patientDirectory, CityHistory cityHistory, CommunityHistory communityHistory, HouseHistory houseHistory, EncounterHistory encounterHistory, DoctorDirectory doctorDirectory, HospitalDirectory hospitalDirectory, Vitals vitals) {
        initComponents();
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.cityHistory = cityHistory;
        this.communityHistory = communityHistory;
        this.houseHistory = houseHistory;
        this.encounterHistory = encounterHistory;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.vitals = vitals;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Communitybtn = new javax.swing.JButton();
        Housebtn = new javax.swing.JButton();
        Personbtn = new javax.swing.JButton();
        Hospitalbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Community");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Admin");

        Communitybtn.setText("Community");
        Communitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitybtnActionPerformed(evt);
            }
        });

        Housebtn.setText("House");
        Housebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HousebtnActionPerformed(evt);
            }
        });

        Personbtn.setText("Person");
        Personbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonbtnActionPerformed(evt);
            }
        });

        Hospitalbtn.setText("Hospital");
        Hospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setText("LogOut");
        LogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Communitybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Housebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Personbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hospitalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(Communitybtn)
                .addGap(18, 18, 18)
                .addComponent(Housebtn)
                .addGap(18, 18, 18)
                .addComponent(Personbtn)
                .addGap(18, 18, 18)
                .addComponent(Hospitalbtn)
                .addGap(18, 18, 18)
                .addComponent(LogOutbtn)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CommunitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitybtnActionPerformed
        // TODO add your handling code here:
        CommunityJPanel communitycud = new CommunityJPanel(communityHistory,cityHistory);
        jSplitPane.setRightComponent(communitycud);
    }//GEN-LAST:event_CommunitybtnActionPerformed

    private void HousebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HousebtnActionPerformed
        // TODO add your handling code here:
        HouseJPanel housecud = new HouseJPanel(houseHistory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(housecud);
    }//GEN-LAST:event_HousebtnActionPerformed

    private void PersonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonbtnActionPerformed
        // TODO add your handling code here:
        PersonJPanel personcud = new PersonJPanel(personDirectory,houseHistory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(personcud);
    }//GEN-LAST:event_PersonbtnActionPerformed

    private void HospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalbtnActionPerformed
        // TODO add your handling code here:
        HospitalJPanel doctorcud = new HospitalJPanel(hospitalDirectory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(doctorcud);
    }//GEN-LAST:event_HospitalbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_LogOutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdminHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Communitybtn;
    private javax.swing.JButton Hospitalbtn;
    private javax.swing.JButton Housebtn;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JButton Personbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
