/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.AppointmentHistory;
import Model.CityHistory;
import Model.CommunityHistory;
import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.HospitalDirectory;
import Model.HouseHistory;
import Model.PatientDirectory;
import Model.PersonDirectory;
import Model.Vitals;

/**
 *
 * @author sumit
 */
public class DoctorHomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoctorHomeJFrame
     */
    public static PersonDirectory personDirectory;
    public static PatientDirectory patientDirectory;
    public static CityHistory cityHistory;
    public static CommunityHistory communityHistory;
    public static HouseHistory houseHistory;
    public static EncounterHistory encounterHistory;
    public static DoctorDirectory doctorDirectory;
    public static HospitalDirectory hospitalDirectory;
    public static AppointmentHistory appointmentHistory;
    public static Vitals vitals;
    public static String username;
    public static String password;
    public static String Doctorname;
    public DoctorHomeJFrame(PersonDirectory personDirectory, PatientDirectory patientDirectory, CityHistory cityHistory, CommunityHistory communityHistory, HouseHistory houseHistory, EncounterHistory encounterHistory, DoctorDirectory doctorDirectory, HospitalDirectory hospitalDirectory, Vitals vitals, AppointmentHistory appointmentHistory, String Username, String Password,String DoctorName) {
        initComponents();
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.cityHistory = cityHistory;
        this.communityHistory = communityHistory;
        this.houseHistory = houseHistory;
        this.encounterHistory = encounterHistory;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.appointmentHistory = appointmentHistory;
        this.vitals = vitals;
        this.username = Username;
        this.password = Password;
        this.Doctorname = DoctorName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Vitalsbtn = new javax.swing.JButton();
        Docotrbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        BookAppbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Back");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Doctor");

        Vitalsbtn.setText("Vitals");
        Vitalsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalsbtnActionPerformed(evt);
            }
        });

        Docotrbtn.setText("Doctor");
        Docotrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocotrbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setText("LogOut");
        LogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbtnActionPerformed(evt);
            }
        });

        BookAppbtn.setText("Appointment");
        BookAppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BookAppbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(Vitalsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addComponent(Docotrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(BookAppbtn)
                .addGap(18, 18, 18)
                .addComponent(Vitalsbtn)
                .addGap(18, 18, 18)
                .addComponent(Docotrbtn)
                .addGap(18, 18, 18)
                .addComponent(LogOutbtn)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VitalsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalsbtnActionPerformed
        // TODO add your handling code here:
        DoctorViewVitalsJPanel docvitals = new DoctorViewVitalsJPanel(patientDirectory, encounterHistory, doctorDirectory,username,password,Doctorname);
        jSplitPane.setRightComponent
(docvitals);
    }//GEN-LAST:event_VitalsbtnActionPerformed

    private void DocotrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocotrbtnActionPerformed
        // TODO add your handling code here:
        DoctorViewDoctorJPanel docdoctor = new DoctorViewDoctorJPanel(doctorDirectory,hospitalDirectory,username,password);
        jSplitPane.setRightComponent(docdoctor);
    }//GEN-LAST:event_DocotrbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_LogOutbtnActionPerformed

    private void BookAppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppbtnActionPerformed
        // TODO add your handling code here:
        DoctorViewAppointmentJPanel viewappointment = new DoctorViewAppointmentJPanel(patientDirectory, encounterHistory, doctorDirectory,cityHistory,communityHistory,hospitalDirectory,appointmentHistory, username,password);
        jSplitPane.setRightComponent(viewappointment);
    }//GEN-LAST:event_BookAppbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals,appointmentHistory,username,password,Doctorname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookAppbtn;
    private javax.swing.JButton Docotrbtn;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JButton Vitalsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
