/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.DoctorDirectory;
import Model.Patient;
import Model.PatientDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author sumit
 */
public class HomeJFrame extends javax.swing.JFrame {
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;

    Patient patient;
    
    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
        patientDirectory = new PatientDirectory();
        doctorDirectory = new DoctorDirectory();
        patient = new Patient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        UserType = new javax.swing.JPanel();
        Patientbtn = new javax.swing.JButton();
        Doctorbtn = new javax.swing.JButton();
        CommAdminbtn = new javax.swing.JButton();
        UserTypelbl = new javax.swing.JLabel();
        SysAdminbtn = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Patientbtn.setText("Patient");
        Patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientbtnActionPerformed(evt);
            }
        });

        Doctorbtn.setText("Doctor");
        Doctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorbtnActionPerformed(evt);
            }
        });

        CommAdminbtn.setText("Community Admin");
        CommAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommAdminbtnActionPerformed(evt);
            }
        });

        UserTypelbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UserTypelbl.setText("User Type");

        SysAdminbtn.setText("System Admin");
        SysAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SysAdminbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserTypeLayout = new javax.swing.GroupLayout(UserType);
        UserType.setLayout(UserTypeLayout);
        UserTypeLayout.setHorizontalGroup(
            UserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(UserTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Patientbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Doctorbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserTypelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(UserTypeLayout.createSequentialGroup()
                        .addComponent(CommAdminbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SysAdminbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        UserTypeLayout.setVerticalGroup(
            UserTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserTypelbl)
                .addGap(44, 44, 44)
                .addComponent(Patientbtn)
                .addGap(36, 36, 36)
                .addComponent(Doctorbtn)
                .addGap(40, 40, 40)
                .addComponent(CommAdminbtn)
                .addGap(37, 37, 37)
                .addComponent(SysAdminbtn)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(UserType);

        javax.swing.GroupLayout WorkAreaLayout = new javax.swing.GroupLayout(WorkArea);
        WorkArea.setLayout(WorkAreaLayout);
        WorkAreaLayout.setHorizontalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        WorkAreaLayout.setVerticalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(WorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientbtnActionPerformed
        // TODO add your handling code here:
        PatientLogInJPanel logPat = new PatientLogInJPanel(patientDirectory,patient);
        jSplitPane.setRightComponent(logPat);
    }//GEN-LAST:event_PatientbtnActionPerformed

    private void DoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorbtnActionPerformed
        // TODO add your handling code here:
       // DoctorLoginJPanel logPat = new DoctorLoginJPanel(emphistory,newEmp);
        //jSplitPane.setRightComponent(logPat);
    }//GEN-LAST:event_DoctorbtnActionPerformed

    private void CommAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommAdminbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommAdminbtnActionPerformed

    private void SysAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysAdminbtnActionPerformed
        // TODO add your handling code here:
        SysAdminLogInJPanel adminLog = new SysAdminLogInJPanel();
        jSplitPane.setRightComponent(adminLog);
    }//GEN-LAST:event_SysAdminbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommAdminbtn;
    private javax.swing.JButton Doctorbtn;
    private javax.swing.JButton Patientbtn;
    private javax.swing.JButton SysAdminbtn;
    private javax.swing.JPanel UserType;
    private javax.swing.JLabel UserTypelbl;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
