/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.AppointmentHistory;
import Model.CityHistory;
import Model.CommunityHistory;
import Model.Doctor;
import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.HospitalDirectory;
import Model.HouseHistory;
import Model.Patient;
import Model.PatientDirectory;
import Model.PersonDirectory;
import Model.Vitals;
import javax.swing.JOptionPane;

/**
 *
 * @author sumit
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    CityHistory cityHistory;
    CommunityHistory communityHistory;
    HouseHistory houseHistory;
    EncounterHistory encounterHistory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    AppointmentHistory appointmentHistory;
    Vitals vitals;
    public HomeJFrame() {
        initComponents();
        patientDirectory = new PatientDirectory();
        doctorDirectory = new DoctorDirectory();
        personDirectory = new PersonDirectory();
        cityHistory = new CityHistory();
        communityHistory = new CommunityHistory();
        houseHistory = new HouseHistory();
        encounterHistory = new EncounterHistory();
        hospitalDirectory = new HospitalDirectory();
        appointmentHistory = new AppointmentHistory();
        vitals = new Vitals();
        UserTypetxt.setEnabled(false);
        LogInbtn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        UserTypelbl1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        UserNamelbl1 = new javax.swing.JLabel();
        UserNametxt = new javax.swing.JTextField();
        Passwordlbl1 = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        UserTypetxt = new javax.swing.JTextField();
        Patientbtn = new javax.swing.JButton();
        Doctorbtn = new javax.swing.JButton();
        HospitalAdminbtn = new javax.swing.JButton();
        SysAdminbtn = new javax.swing.JButton();
        CommAdminbtn = new javax.swing.JButton();
        LogInbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserTypelbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        UserTypelbl1.setText("Welcome");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("to");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("City");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Medical");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(UserTypelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(UserTypelbl1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("LOG IN");

        UserNamelbl1.setText("UserName");

        Passwordlbl1.setText("Password");

        jLabel7.setText("User Type:");

        Patientbtn.setText("Patient");
        Patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientbtnActionPerformed(evt);
            }
        });

        Doctorbtn.setText("Doctor");
        Doctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorbtnActionPerformed(evt);
            }
        });

        HospitalAdminbtn.setText("Hospital Admin");
        HospitalAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalAdminbtnActionPerformed(evt);
            }
        });

        SysAdminbtn.setText("System Admin");
        SysAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SysAdminbtnActionPerformed(evt);
            }
        });

        CommAdminbtn.setText("Community Admin");
        CommAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommAdminbtnActionPerformed(evt);
            }
        });

        LogInbtn.setText("LogIn");
        LogInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserTypetxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Passwordtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserNamelbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserNametxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(219, 219, 219))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LogInbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Passwordlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Patientbtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(Doctorbtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(HospitalAdminbtn))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(CommAdminbtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(SysAdminbtn))))
                        .addGap(126, 126, 126))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(UserNamelbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordlbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Patientbtn)
                    .addComponent(Doctorbtn)
                    .addComponent(HospitalAdminbtn))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommAdminbtn)
                    .addComponent(SysAdminbtn))
                .addGap(18, 18, 18)
                .addComponent(LogInbtn)
                .addGap(0, 279, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientbtnActionPerformed
        // TODO add your handling code here:
        UserTypetxt.setText("Patient");
    }//GEN-LAST:event_PatientbtnActionPerformed

    private void DoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorbtnActionPerformed
        // TODO add your handling code here:
        UserTypetxt.setText("Doctor");
    }//GEN-LAST:event_DoctorbtnActionPerformed

    private void HospitalAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalAdminbtnActionPerformed
        // TODO add your handling code here:
        UserTypetxt.setText("Hospital Admin");
    }//GEN-LAST:event_HospitalAdminbtnActionPerformed

    private void SysAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysAdminbtnActionPerformed
        // TODO add your handling code here:
        UserTypetxt.setText("System Admin");
    }//GEN-LAST:event_SysAdminbtnActionPerformed

    private void CommAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommAdminbtnActionPerformed
        // TODO add your handling code here:
        UserTypetxt.setText("Community Admin");
    }//GEN-LAST:event_CommAdminbtnActionPerformed

    private void LogInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInbtnActionPerformed
        // TODO add your handling code here:
        String userName = UserNametxt.getText();
        char[] passwordCharArray = Passwordtxt.getPassword();
        String password = String.valueOf(passwordCharArray);

        if (userName == null || password == null) {
            JOptionPane.showMessageDialog(null, "Enter valid credentials");
            return;
        }
        else if (userName.equalsIgnoreCase("sysadmin")  && password.equalsIgnoreCase("sysadmin") && UserTypetxt.getText().equalsIgnoreCase("System Admin"))
        {
            SysAdminHomeJFrame sysadhome = new SysAdminHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals);
            sysadhome.setVisible(true);

        }
        else if (!userName.equals("sysadmin")  && !password.equals("sysadmin") && UserTypetxt.getText().equalsIgnoreCase("Doctor"))
        {
            for(Doctor doc : doctorDirectory.docHistory){
                if(doc.getUsername().equalsIgnoreCase(userName) && doc.getPassword().equalsIgnoreCase(password)){
                    DoctorHomeJFrame doctorhome = new DoctorHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals, appointmentHistory,userName,password,doc.getDoctorID());
                    doctorhome.setVisible(true);
                }
            }
        }
        else if (!userName.equals("sysadmin")  && !password.equals("sysadmin") && UserTypetxt.getText().equalsIgnoreCase("Patient"))
        {
            for(Patient pat : patientDirectory.patHistory){
                if(pat.getUsername().equalsIgnoreCase(userName) && pat.getPassword().equalsIgnoreCase(password)){
                    PatientHomeJFrame patienthome = new PatientHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals, appointmentHistory, userName,password);
                    patienthome.setVisible(true);
                }
            }
        }
        else if (userName.equalsIgnoreCase("commadmin")  && password.equalsIgnoreCase("commadmin") && UserTypetxt.getText().equalsIgnoreCase("Community Admin"))
        {
            CommunityAdminHomeJFrame commadminhome = new CommunityAdminHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals);
            commadminhome.setVisible(true);
        }
        else if (userName.equalsIgnoreCase("hospadmin")  && password.equalsIgnoreCase("hospadmin") && UserTypetxt.getText().equalsIgnoreCase("Hospital Admin"))
        {
            HospitalAdminHomeJFrame hospadminhome = new HospitalAdminHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals);  
            hospadminhome.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }

        UserNametxt.setText("");
        Passwordtxt.setText("");
        UserTypetxt.setText("");
    }//GEN-LAST:event_LogInbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommAdminbtn;
    private javax.swing.JButton Doctorbtn;
    private javax.swing.JButton HospitalAdminbtn;
    private javax.swing.JButton LogInbtn;
    private javax.swing.JLabel Passwordlbl1;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JButton Patientbtn;
    private javax.swing.JButton SysAdminbtn;
    private javax.swing.JLabel UserNamelbl1;
    private javax.swing.JTextField UserNametxt;
    private javax.swing.JLabel UserTypelbl1;
    private javax.swing.JTextField UserTypetxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
