/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorDirectory;
import Model.Patient;
import Model.PatientDirectory;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author sumit
 */
public class PatientLogInJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientLogIn
     */
    PatientDirectory patientDirectory;
    Patient patient;
    public PatientLogInJPanel(PatientDirectory patientDirectory, Patient patient) {
        initComponents();
        this.patientDirectory = patientDirectory;
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        FullNametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Agetxt = new javax.swing.JTextField();
        Genderlbl = new javax.swing.JLabel();
        Gendertxt = new javax.swing.JTextField();
        Weightlbl = new javax.swing.JLabel();
        Weighttxt = new javax.swing.JTextField();
        Heighttxt = new javax.swing.JTextField();
        Heightlbl = new javax.swing.JLabel();
        Citytxt = new javax.swing.JTextField();
        Citylbl = new javax.swing.JLabel();
        Communitytxt = new javax.swing.JTextField();
        Communitylbl = new javax.swing.JLabel();
        Streetlbl = new javax.swing.JLabel();
        Streettxt = new javax.swing.JTextField();
        Passwordlbl1 = new javax.swing.JLabel();
        Passwordtxt1 = new javax.swing.JPasswordField();
        SignUpbtn = new javax.swing.JButton();
        IDlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HouseNolbl = new javax.swing.JLabel();
        UserNamelbl1 = new javax.swing.JLabel();
        UserNametxt1 = new javax.swing.JTextField();
        HouseNo = new javax.swing.JTextField();
        IDtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        UserNamelbl = new javax.swing.JLabel();
        UserNametxt = new javax.swing.JTextField();
        Passwordlbl = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        LogInbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();

        jLabel4.setText("Full Name:");

        jLabel5.setText("Age:");

        Genderlbl.setText("Gender:");

        Weightlbl.setText("Weight(in kg):");

        Heightlbl.setText("Height(in cm):");

        Citytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitytxtActionPerformed(evt);
            }
        });

        Citylbl.setText("City:");

        Communitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitytxtActionPerformed(evt);
            }
        });

        Communitylbl.setText("Community:");

        Streetlbl.setText("Street:");

        Passwordlbl1.setText("Password");

        SignUpbtn.setText("SignUp");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });

        IDlbl.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SIGN UP");

        HouseNolbl.setText("House Number:");

        UserNamelbl1.setText("UserName");

        UserNametxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNametxt1ActionPerformed(evt);
            }
        });

        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LOG IN");

        UserNamelbl.setText("UserName");

        Passwordlbl.setText("Password");

        LogInbtn.setText("LogIn");
        LogInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setText("LogOut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Passwordtxt)
                            .addComponent(UserNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserNametxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Passwordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LogInbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(LogOutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Weighttxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Weightlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Genderlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gendertxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullNametxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Agetxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Streetlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Communitylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Citylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Citytxt)
                            .addComponent(Communitytxt)
                            .addComponent(Streettxt)
                            .addComponent(HouseNolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Heighttxt)
                            .addComponent(Heightlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(HouseNo))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserNametxt1)
                            .addComponent(Passwordtxt1)
                            .addComponent(Passwordlbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserNamelbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignUpbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlbl)
                    .addComponent(HouseNolbl)
                    .addComponent(UserNamelbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserNametxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Streetlbl)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Streettxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Communitylbl)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Communitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Citylbl)
                            .addComponent(Genderlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Weightlbl)
                            .addComponent(Heightlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Weighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Heighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Passwordlbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Passwordtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SignUpbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserNamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInbtn)
                    .addComponent(LogOutbtn))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitytxtActionPerformed

    private void CommunitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunitytxtActionPerformed

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        // TODO add your handling code here:
        try{
            if (EmpStartDatejdc.getDate()!= null){                
                if (validate(EmpNametf.getText(),EmpIdtf.getText(),EmpAgetf.getText(),EmpStartDatejdc.getDate(),EmpNumbertf.getText(),EmpEmailtf.getText())){
            String EmpName = EmpNametf.getText();
            String EmpId = EmpIdtf.getText();
            int EmpAge = Integer.parseInt(EmpAgetf.getText());
            String EmpGender = EmpGendertf.getText();
            Date EmpStartDate = EmpStartDatejdc.getDate();
            String EmpLevel = EmpLeveltf.getText();
            String EmpTeam = EmpTeamtf.getText();
            String EmpPosition = EmpPositiontf.getText();
            Long EmpNumber = Long.parseLong(EmpNumbertf.getText());
            String EmpEmail = EmpEmailtf.getText();
            
            newEmp = employeehistory.addNewValue();
            newEmp.setEmpName(EmpName);
            newEmp.setEmpId(EmpId);
            newEmp.setEmpAge(EmpAge);
            newEmp.setEmpGender(EmpGender);
            newEmp.setEmpStartDate(EmpStartDate);
            newEmp.setEmpLevel(EmpLevel);
            newEmp.setEmpTeam(EmpTeam);
            newEmp.setEmpPosition(EmpPosition);
            newEmp.setEmpNumber(EmpNumber);
            newEmp.setEmpEmail(EmpEmail);
            newEmp.setImage(img);
            
            JOptionPane.showMessageDialog(this, "Successfully added new Employee");
            
            EmpNametf.setText("");
            EmpIdtf.setText("");
            EmpAgetf.setText("");
            EmpGendertf.setText("");
            EmpStartDatejdc.setDate(null);
            EmpLeveltf.setText("");
            EmpTeamtf.setText("");
            EmpPositiontf.setText("");
            EmpNumbertf.setText("");
            EmpEmailtf.setText("");
            lblImagePreview.setIcon(null);
            //lblImagePreview.setDisabledIcon(null);
            }
            }
                else{
                    JOptionPane.showMessageDialog(EmpStartDatelbl, "Start Date cannot null", "Error", JOptionPane.ERROR_MESSAGE);
                }
        }
        catch(NumberFormatException e){
            System.out.print(e);
        }
    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void UserNametxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNametxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNametxt1ActionPerformed

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxtActionPerformed

    private void LogInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInbtnActionPerformed
        // TODO add your handling code here:
        String userName = UserNametxt.getText();
        char[] passwordCharArray = Passwordtxt.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount userAccount = system.UserAccountDirectory()
        .authenticateUser(userName, password);

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }else{
            CardLayout layout = (CardLayout)WorkArea.getLayout();
            WorkArea.add("workArea", userAccount.getRole().createWorkArea(WorkArea, userAccount, system));
            layout.next(WorkArea);
        }

        LogInbtn.setEnabled(false);
        UserNametxt.setEnabled(false);
        Passwordtxt.setEnabled(false);
    }//GEN-LAST:event_LogInbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agetxt;
    private javax.swing.JLabel Citylbl;
    private javax.swing.JTextField Citytxt;
    private javax.swing.JLabel Communitylbl;
    private javax.swing.JTextField Communitytxt;
    private javax.swing.JTextField FullNametxt;
    private javax.swing.JLabel Genderlbl;
    private javax.swing.JTextField Gendertxt;
    private javax.swing.JLabel Heightlbl;
    private javax.swing.JTextField Heighttxt;
    private javax.swing.JTextField HouseNo;
    private javax.swing.JLabel HouseNolbl;
    private javax.swing.JLabel IDlbl;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton LogInbtn;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JLabel Passwordlbl1;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JPasswordField Passwordtxt1;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JLabel Streetlbl;
    private javax.swing.JTextField Streettxt;
    private javax.swing.JLabel UserNamelbl;
    private javax.swing.JLabel UserNamelbl1;
    private javax.swing.JTextField UserNametxt;
    private javax.swing.JTextField UserNametxt1;
    private javax.swing.JLabel Weightlbl;
    private javax.swing.JTextField Weighttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

public static final Pattern pattern = 
    Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean EmailValidate(String emailStr) {
            Matcher matcher = pattern.matcher(emailStr);
            return matcher.find();
    }
    private boolean validate(String EmpName, String EmpId , String EmpAge, Date EmpStartDate, String EmpNumber, String EmpEmail) {
        
        if(EmpName.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Name Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpId.length()==0){
            JOptionPane.showMessageDialog(this, "Employee ID Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpAge.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Age Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpStartDate.after((java.util.Calendar.getInstance().getTime()))){
            JOptionPane.showMessageDialog(EmpStartDatelbl, "Start Date cannot be a future date", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        
        if(EmpNumber.length()>10 || EmpNumber.length()==0 || EmpNumber.length()<10){
            JOptionPane.showMessageDialog(this, "Enter a valid 10 digit Number", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpEmail.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Email Address Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        if(!EmailValidate(EmpEmail)){
            JOptionPane.showMessageDialog(this, "Enter Valid Employee Email", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        else {
            return true; }
    }
}
