/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorDirectory;
import Model.Encounter;
import Model.EncounterHistory;
import Model.Patient;
import Model.PatientDirectory;
import Model.Vitals;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumit
 */
public class PatientViewVitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientViewVitalsJPanel
     */
    PatientDirectory patientDirectory;
    EncounterHistory encounterHistory;
    DoctorDirectory doctorDirectory;
    String Username;
    String Password;
    public PatientViewVitalsJPanel(PatientDirectory patientDirectory, EncounterHistory encounterHistory, DoctorDirectory doctorDirectory, String username, String password) {
        initComponents();
        this.patientDirectory = patientDirectory;
        this.encounterHistory = encounterHistory;
        this.doctorDirectory = doctorDirectory;
        Username = username;
        Password = password;
        populateTable();
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)VitalsJTable.getModel();
        model.setRowCount(0);
        for(Patient pats: patientDirectory.getPatHistory()){
        for(Encounter encounter: encounterHistory.getEncHistory()){
            if(pats.getUsername().equals(Username) && pats.getPassword().equals(Password)){
            Vitals vitals = encounter.getVitals();
            Object[] row = new Object[6];
            row[0] = vitals.getEncounterNumber();
            row[1] = vitals.getPatientName();
            row[2] = vitals.getBloodPressure();
            row[3] = vitals.getTemperature();            
            row[4] = vitals.getPulse();
            row[5] = vitals.getDoctorName();
            model.addRow(row);
        }
    }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vitalslbl = new javax.swing.JLabel();
        PatientIDlbl1 = new javax.swing.JLabel();
        EncounterNumbertxt = new javax.swing.JTextField();
        PatientIDlbl = new javax.swing.JLabel();
        PatientIDtxt = new javax.swing.JTextField();
        Temperaturelbl = new javax.swing.JLabel();
        Temperaturetxt = new javax.swing.JTextField();
        BloodPressurelbl = new javax.swing.JLabel();
        BloodPressuretxt = new javax.swing.JTextField();
        Pulselbl = new javax.swing.JLabel();
        Pulsetxt = new javax.swing.JTextField();
        Doctorlbl = new javax.swing.JLabel();
        Doctortxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        VitalsJTable = new javax.swing.JTable();

        Vitalslbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Vitalslbl.setText("Vitals");

        PatientIDlbl1.setText("Encounter No:");

        PatientIDlbl.setText("Patient Name:");

        Temperaturelbl.setText("Temperature:");

        BloodPressurelbl.setText("Blood Pressure:");

        Pulselbl.setText("Pulse:");

        Doctorlbl.setText("Doctor Name:");

        VitalsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Encounter No.", "Patient Name", "Temperature", "Blood Pressure", "Pulse", "Doctor Name"
            }
        ));
        VitalsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VitalsJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VitalsJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(Vitalslbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pulselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Doctorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Doctortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Temperaturelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BloodPressurelbl)
                                    .addComponent(PatientIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatientIDtxt)
                                    .addComponent(BloodPressuretxt)
                                    .addComponent(Temperaturetxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PatientIDlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(EncounterNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Vitalslbl)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientIDlbl1)
                    .addComponent(EncounterNumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientIDlbl)
                    .addComponent(PatientIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperaturelbl)
                    .addComponent(Temperaturetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodPressurelbl)
                    .addComponent(BloodPressuretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pulselbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctorlbl)
                    .addComponent(Doctortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VitalsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VitalsJTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_VitalsJTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressurelbl;
    private javax.swing.JTextField BloodPressuretxt;
    private javax.swing.JLabel Doctorlbl;
    private javax.swing.JTextField Doctortxt;
    private javax.swing.JTextField EncounterNumbertxt;
    private javax.swing.JLabel PatientIDlbl;
    private javax.swing.JLabel PatientIDlbl1;
    private javax.swing.JTextField PatientIDtxt;
    private javax.swing.JLabel Pulselbl;
    private javax.swing.JTextField Pulsetxt;
    private javax.swing.JLabel Temperaturelbl;
    private javax.swing.JTextField Temperaturetxt;
    private javax.swing.JTable VitalsJTable;
    private javax.swing.JLabel Vitalslbl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
