/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.CityHistory;
import Model.CommunityHistory;
import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.HospitalDirectory;
import Model.HouseHistory;
import Model.PatientDirectory;
import Model.PersonDirectory;
import Model.Vitals;

/**
 *
 * @author sumit
 */
public class SysAdminHomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SysAdminHomeJFrame
     */
    public static PersonDirectory personDirectory;
    public static PatientDirectory patientDirectory;
    public static CityHistory cityHistory;
    public static CommunityHistory communityHistory;
    public static HouseHistory houseHistory;
    public static EncounterHistory encounterHistory;
    public static DoctorDirectory doctorDirectory;
    public static HospitalDirectory hospitalDirectory;
    public static Vitals vitals;
    public SysAdminHomeJFrame(PersonDirectory personDirectory, PatientDirectory patientDirectory, CityHistory cityHistory, CommunityHistory communityHistory, HouseHistory houseHistory, EncounterHistory encounterHistory, DoctorDirectory doctorDirectory, HospitalDirectory hospitalDirectory, Vitals vitals) {
        initComponents();
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.cityHistory = cityHistory;
        this.communityHistory = communityHistory;
        this.houseHistory = houseHistory;
        this.encounterHistory = encounterHistory;
        this.doctorDirectory = doctorDirectory;
        this.hospitalDirectory = hospitalDirectory;
        this.vitals = vitals;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Citybtn = new javax.swing.JButton();
        Communitybtn = new javax.swing.JButton();
        Housebtn = new javax.swing.JButton();
        Hospitalbtn = new javax.swing.JButton();
        Personbtn = new javax.swing.JButton();
        Docotrbtn = new javax.swing.JButton();
        Patientbtn = new javax.swing.JButton();
        Vitalsbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Admin!");

        Citybtn.setText("City");
        Citybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitybtnActionPerformed(evt);
            }
        });

        Communitybtn.setText("Community");
        Communitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunitybtnActionPerformed(evt);
            }
        });

        Housebtn.setText("House");
        Housebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HousebtnActionPerformed(evt);
            }
        });

        Hospitalbtn.setText("Hospital");
        Hospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalbtnActionPerformed(evt);
            }
        });

        Personbtn.setText("Person");
        Personbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonbtnActionPerformed(evt);
            }
        });

        Docotrbtn.setText("Doctor");
        Docotrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocotrbtnActionPerformed(evt);
            }
        });

        Patientbtn.setText("Patient");
        Patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientbtnActionPerformed(evt);
            }
        });

        Vitalsbtn.setText("Vitals");
        Vitalsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalsbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setText("LogOut");
        LogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Citybtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Communitybtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(Housebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hospitalbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Personbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Docotrbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Patientbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Vitalsbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Citybtn)
                .addGap(18, 18, 18)
                .addComponent(Communitybtn)
                .addGap(18, 18, 18)
                .addComponent(Housebtn)
                .addGap(18, 18, 18)
                .addComponent(Hospitalbtn)
                .addGap(18, 18, 18)
                .addComponent(Personbtn)
                .addGap(18, 18, 18)
                .addComponent(Docotrbtn)
                .addGap(18, 18, 18)
                .addComponent(Patientbtn)
                .addGap(18, 18, 18)
                .addComponent(Vitalsbtn)
                .addGap(18, 18, 18)
                .addComponent(LogOutbtn)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitybtnActionPerformed
        // TODO add your handling code here:
        CityJPanel citycud = new CityJPanel(cityHistory);
        jSplitPane.setRightComponent(citycud);
    }//GEN-LAST:event_CitybtnActionPerformed

    private void CommunitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunitybtnActionPerformed
        // TODO add your handling code here:
        CommunityJPanel communitycud = new CommunityJPanel(communityHistory,cityHistory);
        jSplitPane.setRightComponent(communitycud);
    }//GEN-LAST:event_CommunitybtnActionPerformed

    private void HousebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HousebtnActionPerformed
        // TODO add your handling code here:
        HouseJPanel housecud = new HouseJPanel(houseHistory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(housecud);
    }//GEN-LAST:event_HousebtnActionPerformed

    private void HospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalbtnActionPerformed
        // TODO add your handling code here:
        HospitalJPanel doctorcud = new HospitalJPanel(hospitalDirectory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(doctorcud);
    }//GEN-LAST:event_HospitalbtnActionPerformed

    private void PersonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonbtnActionPerformed
        // TODO add your handling code here:
        PersonJPanel personcud = new PersonJPanel(personDirectory,houseHistory,cityHistory,communityHistory);
        jSplitPane.setRightComponent(personcud);
    }//GEN-LAST:event_PersonbtnActionPerformed

    private void DocotrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocotrbtnActionPerformed
        // TODO add your handling code here:
        DoctorJPanel doctorcud = new DoctorJPanel(doctorDirectory,hospitalDirectory);
        jSplitPane.setRightComponent(doctorcud);
    }//GEN-LAST:event_DocotrbtnActionPerformed

    private void PatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientbtnActionPerformed
        // TODO add your handling code here:
        PatientJPanel patientcud = new PatientJPanel(patientDirectory,personDirectory);
        jSplitPane.setRightComponent(patientcud);
    }//GEN-LAST:event_PatientbtnActionPerformed

    private void VitalsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalsbtnActionPerformed
        // TODO add your handling code here:
        VitalsJPanel vitalscud = new VitalsJPanel(patientDirectory, encounterHistory, doctorDirectory);
        jSplitPane.setRightComponent(vitalscud);
    }//GEN-LAST:event_VitalsbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_LogOutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysAdminHomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysAdminHomeJFrame(personDirectory, patientDirectory, cityHistory, communityHistory, houseHistory, encounterHistory, doctorDirectory, hospitalDirectory, vitals).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Citybtn;
    private javax.swing.JButton Communitybtn;
    private javax.swing.JButton Docotrbtn;
    private javax.swing.JButton Hospitalbtn;
    private javax.swing.JButton Housebtn;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JButton Patientbtn;
    private javax.swing.JButton Personbtn;
    private javax.swing.JButton Vitalsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
